// <auto-generated />
using System;
using Level5.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Level5.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(Level5V2DbContext))]
    [Migration("20260926134216_AddLegacyMatchResultLinks")]
    partial class AddLegacyMatchResultLinks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Level5.Infrastructure.Persistence.Rows.AccountRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("EmailCanonical")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("UsernameCanonical")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("EmailCanonical")
                        .IsUnique();

                    b.HasIndex("UsernameCanonical")
                        .IsUnique();

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Level5.Infrastructure.Persistence.Rows.AuthSessionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique();

                    b.ToTable("auth_sessions", (string)null);
                });

            modelBuilder.Entity("Level5.Infrastructure.Persistence.Rows.FriendRequestRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FromPlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LowerPlayerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("ToPlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UpperPlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UpperPlayerId");

                    b.HasIndex("FromPlayerId", "Status");

                    b.HasIndex("FromPlayerId", "ToPlayerId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Pending'");

                    b.HasIndex("LowerPlayerId", "UpperPlayerId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Pending'");

                    b.HasIndex("ToPlayerId", "Status");

                    b.ToTable("friend_requests", (string)null);
                });

            modelBuilder.Entity("Level5.Infrastructure.Persistence.Rows.FriendshipRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LowerPlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UpperPlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UpperPlayerId");

                    b.HasIndex("LowerPlayerId", "UpperPlayerId")
                        .IsUnique();

                    b.ToTable("friendships", (string)null);
                });

            modelBuilder.Entity("Level5.Infrastructure.Persistence.Rows.LegacyAccountLinkRow", b =>
                {
                    b.Property<int>("LegacyUserId")
                        .HasColumnType("integer");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("LegacyUsername")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTimeOffset>("MigratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("LegacyUserId");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("legacy_account_links", (string)null);
                });

            modelBuilder.Entity("Level5.Infrastructure.Persistence.Rows.LegacyMatchResultLinkRow", b =>
                {
                    b.Property<int>("LegacyHighscoreId")
                        .HasColumnType("integer");

                    b.Property<string>("LegacyScoreId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("MatchResultId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("MigratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LegacyHighscoreId");

                    b.HasIndex("MatchResultId")
                        .IsUnique();

                    b.ToTable("legacy_match_result_links", (string)null);
                });

            modelBuilder.Entity("Level5.Infrastructure.Persistence.Rows.MatchResultRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CharacterId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ClientResultId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LevelId")
                        .HasColumnType("integer");

                    b.Property<string>("MetricsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("ModeId")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiersJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ModeId");

                    b.HasIndex("PlayerId", "ClientResultId")
                        .IsUnique();

                    b.ToTable("match_results", (string)null);
                });

            modelBuilder.Entity("Level5.Infrastructure.Persistence.Rows.PlayerProfileRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("Tag")
                        .IsUnique();

                    b.ToTable("player_profiles", (string)null);
                });

            modelBuilder.Entity("Level5.Infrastructure.Persistence.Rows.VersusSeriesRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChallengerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClientRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentGameNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("OpponentId")
                        .HasColumnType("uuid");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<int>("TotalGames")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WinnerId");

                    b.HasIndex("ChallengerId", "ClientRequestId")
                        .IsUnique();

                    b.HasIndex("ChallengerId", "Status");

                    b.HasIndex("OpponentId", "Status");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("competitive_series", (string)null);
                });

            modelBuilder.Entity("Level5.Infrastructure.Persistence.Rows.AuthSessionRow", b =>
                {
                    b.HasOne("Level5.Infrastructure.Persistence.Rows.AccountRow", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Level5.Infrastructure.Persistence.Rows.FriendRequestRow", b =>
                {
                    b.HasOne("Level5.Infrastructure.Persistence.Rows.PlayerProfileRow", null)
                        .WithMany()
                        .HasForeignKey("FromPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Level5.Infrastructure.Persistence.Rows.PlayerProfileRow", null)
                        .WithMany()
                        .HasForeignKey("LowerPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Level5.Infrastructure.Persistence.Rows.PlayerProfileRow", null)
                        .WithMany()
                        .HasForeignKey("ToPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Level5.Infrastructure.Persistence.Rows.PlayerProfileRow", null)
                        .WithMany()
                        .HasForeignKey("UpperPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Level5.Infrastructure.Persistence.Rows.FriendshipRow", b =>
                {
                    b.HasOne("Level5.Infrastructure.Persistence.Rows.PlayerProfileRow", null)
                        .WithMany()
                        .HasForeignKey("LowerPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Level5.Infrastructure.Persistence.Rows.PlayerProfileRow", null)
                        .WithMany()
                        .HasForeignKey("UpperPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Level5.Infrastructure.Persistence.Rows.LegacyAccountLinkRow", b =>
                {
                    b.HasOne("Level5.Infrastructure.Persistence.Rows.AccountRow", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Level5.Infrastructure.Persistence.Rows.PlayerProfileRow", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Level5.Infrastructure.Persistence.Rows.LegacyMatchResultLinkRow", b =>
                {
                    b.HasOne("Level5.Infrastructure.Persistence.Rows.MatchResultRow", null)
                        .WithMany()
                        .HasForeignKey("MatchResultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Level5.Infrastructure.Persistence.Rows.MatchResultRow", b =>
                {
                    b.HasOne("Level5.Infrastructure.Persistence.Rows.PlayerProfileRow", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Level5.Infrastructure.Persistence.Rows.PlayerProfileRow", b =>
                {
                    b.HasOne("Level5.Infrastructure.Persistence.Rows.AccountRow", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Level5.Infrastructure.Persistence.Rows.VersusSeriesRow", b =>
                {
                    b.HasOne("Level5.Infrastructure.Persistence.Rows.PlayerProfileRow", null)
                        .WithMany()
                        .HasForeignKey("ChallengerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Level5.Infrastructure.Persistence.Rows.PlayerProfileRow", null)
                        .WithMany()
                        .HasForeignKey("OpponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Level5.Infrastructure.Persistence.Rows.PlayerProfileRow", null)
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
