// <auto-generated />
using System;
using Level5Backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Level5Backend.Migrations
{
    [DbContext(typeof(Level5Context))]
    [Migration("20261004221100_MakeUserReportAttributionNullable")]
    partial class MakeUserReportAttributionNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Level5Backend.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentVersion")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("currentVersion");

                    b.HasKey("Id");

                    b.HasIndex("CurrentVersion")
                        .IsUnique();

                    b.ToTable("Application", (string)null);
                });

            modelBuilder.Entity("Level5Backend.Models.Highscore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BonusPoints")
                        .HasColumnType("integer")
                        .HasColumnName("bonusPoints");

                    b.Property<string>("Character")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("character");

                    b.Property<int>("Characterid")
                        .HasColumnType("integer")
                        .HasColumnName("characterid");

                    b.Property<int>("ConsecutiveShots")
                        .HasColumnType("integer")
                        .HasColumnName("consecutiveShots");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("date");

                    b.Property<string>("Device")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("device")
                        .HasComment("what specific device being used");

                    b.Property<int?>("Difficulty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("difficulty")
                        .HasDefaultValueSql("'1'");

                    b.Property<int>("EnemiesEnabled")
                        .HasColumnType("integer")
                        .HasColumnName("enemiesEnabled");

                    b.Property<int>("EnemiesKilled")
                        .HasColumnType("integer")
                        .HasColumnName("enemiesKilled");

                    b.Property<string>("FirstPlace")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("firstPlace");

                    b.Property<int?>("FourAtt")
                        .HasColumnType("integer")
                        .HasColumnName("fourAtt");

                    b.Property<int?>("FourMade")
                        .HasColumnType("integer")
                        .HasColumnName("fourMade");

                    b.Property<string>("FourthPlace")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fourthPlace");

                    b.Property<int>("HardcoreEnabled")
                        .HasColumnType("integer")
                        .HasColumnName("hardcoreEnabled");

                    b.Property<string>("Ipaddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ipaddress");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("level");

                    b.Property<int>("Levelid")
                        .HasColumnType("integer")
                        .HasColumnName("levelid");

                    b.Property<float>("LongestShot")
                        .HasColumnType("real")
                        .HasColumnName("longestShot");

                    b.Property<int>("MaxShotAtt")
                        .HasColumnType("integer")
                        .HasColumnName("maxShotAtt");

                    b.Property<int>("MaxShotMade")
                        .HasColumnType("integer")
                        .HasColumnName("maxShotMade");

                    b.Property<string>("ModeName")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("modeName");

                    b.Property<int>("Modeid")
                        .HasColumnType("integer")
                        .HasColumnName("modeid");

                    b.Property<int?>("MoneyBallAtt")
                        .HasColumnType("integer")
                        .HasColumnName("moneyBallAtt");

                    b.Property<int?>("MoneyBallMade")
                        .HasColumnType("integer")
                        .HasColumnName("moneyBallMade");

                    b.Property<int>("NumPlayers")
                        .HasColumnType("integer")
                        .HasColumnName("numPlayers");

                    b.Property<string>("Os")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("os");

                    b.Property<int>("P1IsCpu")
                        .HasColumnType("integer")
                        .HasColumnName("p1IsCpu");

                    b.Property<int>("P1TotalPoints")
                        .HasColumnType("integer")
                        .HasColumnName("p1TotalPoints");

                    b.Property<int>("P2IsCpu")
                        .HasColumnType("integer")
                        .HasColumnName("p2IsCpu");

                    b.Property<int>("P2TotalPoints")
                        .HasColumnType("integer")
                        .HasColumnName("p2TotalPoints");

                    b.Property<int>("P3IsCpu")
                        .HasColumnType("integer")
                        .HasColumnName("p3IsCpu");

                    b.Property<int>("P3TotalPoints")
                        .HasColumnType("integer")
                        .HasColumnName("p3TotalPoints");

                    b.Property<int>("P4IsCpu")
                        .HasColumnType("integer")
                        .HasColumnName("p4IsCpu");

                    b.Property<int>("P4TotalPoints")
                        .HasColumnType("integer")
                        .HasColumnName("p4TotalPoints");

                    b.Property<string>("Platform")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("platform")
                        .HasComment("if desktop/mobile");

                    b.Property<string>("Scoreid")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("scoreid")
                        .HasComment("unique");

                    b.Property<string>("SecondPlace")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("secondPlace");

                    b.Property<int?>("SevenAtt")
                        .HasColumnType("integer")
                        .HasColumnName("sevenAtt");

                    b.Property<int?>("SevenMade")
                        .HasColumnType("integer")
                        .HasColumnName("sevenMade");

                    b.Property<int>("SniperEnabled")
                        .HasColumnType("integer")
                        .HasColumnName("sniperEnabled");

                    b.Property<int>("SniperHits")
                        .HasColumnType("integer")
                        .HasColumnName("sniperHits");

                    b.Property<int>("SniperMode")
                        .HasColumnType("integer")
                        .HasColumnName("sniperMode");

                    b.Property<string>("SniperModeName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("sniperModeName")
                        .HasDefaultValueSql("'none'");

                    b.Property<int>("SniperShots")
                        .HasColumnType("integer")
                        .HasColumnName("sniperShots");

                    b.Property<string>("ThirdPlace")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("thirdPlace");

                    b.Property<int?>("ThreeAtt")
                        .HasColumnType("integer")
                        .HasColumnName("threeAtt");

                    b.Property<int?>("ThreeMade")
                        .HasColumnType("integer")
                        .HasColumnName("threeMade");

                    b.Property<float>("Time")
                        .HasColumnType("real")
                        .HasColumnName("time");

                    b.Property<float>("TotalDistance")
                        .HasColumnType("real")
                        .HasColumnName("totalDistance");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer")
                        .HasColumnName("totalPoints");

                    b.Property<int>("TrafficEnabled")
                        .HasColumnType("integer")
                        .HasColumnName("trafficEnabled");

                    b.Property<int?>("TwoAtt")
                        .HasColumnType("integer")
                        .HasColumnName("twoAtt");

                    b.Property<int?>("TwoMade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("twoMade")
                        .HasDefaultValueSql("'0'");

                    b.Property<int>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.Property<string>("Username")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("username");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Scoreid")
                        .IsUnique();

                    b.HasIndex("Modeid", "Userid");

                    b.ToTable("highscores", (string)null);
                });

            modelBuilder.Entity("Level5Backend.Models.ServerMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Date")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("date");

                    b.Property<string>("Message")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("message");

                    b.HasKey("Id");

                    b.ToTable("ServerMessages");
                });

            modelBuilder.Entity("Level5Backend.Models.ServerStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float?>("LongestShot")
                        .HasColumnType("real");

                    b.Property<string>("LongestShotUsername")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<int?>("MostConsecutiveShots")
                        .HasColumnType("integer");

                    b.Property<string>("MostConsecutiveShotsUsername")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("MostPlayedCharacter")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("MostPlayedLevel")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<int?>("NumberOfGamesPlayed")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfGamesPlayedHardcore")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfTotal2ShotsAtt")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfTotal2ShotsMade")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfTotal3ShotsAtt")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfTotal3ShotsMade")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfTotal4ShotsAtt")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfTotal4ShotsMade")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfTotal7ShotsAtt")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfTotal7ShotsMade")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfTotalEnemiesKilled")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfTotalMoneyShotsAtt")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfTotalMoneyShotsMade")
                        .HasColumnType("integer");

                    b.Property<float?>("NumberOfTotalTimePlayed")
                        .HasColumnType("real");

                    b.Property<int?>("NumberOfTotalTotalPointsScored")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfTotalTotalShotsAtt")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfTotalTotalShotsMade")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfUsers")
                        .HasColumnType("integer")
                        .HasColumnName("numberOfUsers");

                    b.Property<int?>("NumberofGamesPlayedEnemies")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberofGamesPlayedSniper")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberofGamesPlayedTraffic")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ServerStats");
                });

            modelBuilder.Entity("Level5Backend.Models.User", b =>
                {
                    b.Property<int>("Userid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Userid"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("email");

                    b.Property<string>("Firstname")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("firstname");

                    b.Property<string>("Ipaddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ipaddress");

                    b.Property<int?>("Isdev")
                        .HasColumnType("integer")
                        .HasColumnName("isdev");

                    b.Property<string>("Lastlogin")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("lastlogin");

                    b.Property<string>("Lastname")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("lastname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<string>("Signupdate")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("signupdate");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("username");

                    b.HasKey("Userid");

                    b.HasIndex("Userid")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Level5Backend.Models.UserReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Device")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("device");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("deviceName");

                    b.Property<string>("Ipaddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ipaddress");

                    b.Property<string>("Os")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("os");

                    b.Property<string>("Report")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("report");

                    b.Property<string>("UserName")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("userName");

                    b.Property<int?>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("UserReport", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
